reproducibility_configs:
    "reproduce": False
    "random_seed": None

dataloader_configs:
    "batch_size": 32
    "shuffle": True

circuit_configs:
    "mask_method": "continuous_sparsification"
    "mask_hparams":
        "ablation": "none"
        "mask_unit": "weight"
        "mask_bias": False
        "mask_init_value": -0.1
    "freeze_base" : True
    "add_l0" : True
    "l0_lambda" : 1.0e-7

train_configs:
    "n_epochs": 100
    "final_temp": 100
    "model_path": "checkpoints/resnet18_16class"
    "output_path": "checkpoints/resnet18_ablated_trainable_readout"
    "verbose": True # Will print more intermediate status if True

### Optimizer configs
optim_configs:
    "optim_name": "AdamW" # Name of any optimizer class in torch.nn.optim
    "lr": 1.0e-3 