reproducibility_configs:
    "reproduce": False
    "random_seed": None

dataloader_configs:
    "batch_size": 128
    "num_workers": 4
    "shuffle": True

circuit_configs:
    "mask_method": "continuous_sparsification"
    "mask_hparams":
        "ablation": "none"
        "mask_unit": "weight"
        "mask_bias": False
        "mask_init_value": -0.1
    "freeze_base" : True
    "add_l0" : True
    "l0_lambda" : 1.0e-8

train_configs:
    "n_epochs": 20
    "inherit_from": "random"
    "hf_pretrained": "microsoft/resnet-18" # Pretrained to load for original ResNet & Feature Extractor    
    "output_path": "checkpoints/resnet18_transfer_from_scratch"
    "verbose": True # Will print more intermediate status if True

### Optimizer configs
optim_configs:
    "optim_name": "SGD" # Name of any optimizer class in torch.nn.optim
    "momentum": 0.9
    "weight_decay": 0.0001
    "lr": 1.0e-3