data_configs:
    "max": 1000
    "p": 7
    "n_disambiguation": [0, 10, 20, 50, 100, 200, 500, 1000, 5000]

model_paths:
    "original": "checkpoints/2layers/base"
    "subnet": "checkpoints/2layers/subnet/best_circuit_model.pt"
    #"original": "checkpoints/a+ab_12layers/checkpoint-17000"
    #"subnet": "checkpoints/a+ab_ab_subnetwork/best_circuit_model.pt"

circuit_configs:
    "mask_method": "continuous_sparsification"
    "mask_hparams":
        "ablation": "none"
        "mask_unit": "weight"
        "mask_bias": False
        "mask_init_value": -0.1
    "freeze_base" : False # Must be False since we're no longer doing subnet ablation
    "add_l0" : False

train_configs:
    "n_epochs": 100
    "batch_size": 50
    "inherit_from": original # Should be one of "subnet", "original", or "random"
    "verbose": False
    "wandb": False
    "output_path": "checkpoints/2layers_transfer/original"

### Optimizer configs
optim_configs:
    "optim_name": "AdamW" # Name of any optimizer class in torch.nn.optim
    "lr": [1.0e-3, 5.0e-4]
