reproducibility_configs:
    "reproduce": False
    "random_seed": None

data_configs:
    "max": 1000
    "p": 7
    "n_disambiguation": [0, 10, 16, 25, 40, 64, 100, 160, 250, 400, 640, 1000, 1600, 2500, 4000, 6400, 10000]

model_paths:
    "original": "checkpoints/4layers_val/base"
    "subnet": "checkpoints/4layers_val/subnet_1e-7/best_circuit_model.pt"

circuit_configs:
    "mask_method": "continuous_sparsification"
    "mask_hparams":
        "ablation": "none"
        "mask_unit": "weight"
        "mask_bias": False
        "mask_init_value": -0.1
    "freeze_base" : False # Must be False since we're no longer doing subnet ablation
    "add_l0" : False

train_configs:
    "n_epochs": 100
    "batch_size": 50
    # Should be one of "subnet", "subnet_sampled", "subnet_sampled_complement", "original", or "random"
    "inherit_from": [subnet, subnet_sampled, subnet_sampled_complement, original, random] 
    "freeze_subnet": False
    "verbose": False
    "wandb": False
    "output_path": "checkpoints/4layers_val/transfer_1e-7_trainable"

### Optimizer configs
optim_configs:
    "optim_name": "AdamW" # Name of any optimizer class in torch.nn.optim
    "lr": [2.0e-4]
